### ISSUE TITLE
MTG Goldfish Support

### ISSUE THREAD

**Issue by TekEffekt** [Hottemax/MtgCsvHelper#1]
Hello! It would be wonderful if you could support the CSV format used by MTG Goldfish. The only way to import Goldfish csv's is with their paid subscription. So if there was a way to translate that format into another site's CSV with a free import plan that would be very useful.

**Comment by Hottemax** [comment]
Hi, you can test that with the new version. Let me know how it goes. Thanks.

**Comment by Hottemax** [comment]
@TekEffekt Just tagging to letting you know this is now also available via the [web app](https://hottemax.github.io/MtgCsvHelper)
