### ISSUE TITLE
Tried to convert from MTGGOLDFISH to DRAGONSHIELD and I got an error

### ISSUE THREAD

**Issue by gabrieldesouza02** [Hottemax/MtgCsvHelper#2]
Here is the command I ran along with the error I am getting
![image](https://github.com/Hottemax/MtgCsvHelper/assets/47791612/55622207-2fe7-4dc5-965d-51cb12ae1097)

Here is the list I am using. I exported this list from mtggoldfish, I realize that it's a txt file and that might just be the reason that this error is happening, but I don't know how else to get a list from mtg gold fish that isn't a txt file. this tool is amazing and it would save me a lot of headache if I could get it to work :)
[FaeDominion.txt](https://github.com/Hottemax/MtgCsvHelper/files/12734157/FaeDominion.txt)

**Comment by Hottemax** [comment]
Hi, the tool is mainly for converting between the different csv formats, currently not plain text.
Also, it seems your list is a deck list, not really a collection.

In DragonShield, you can import your decklist by pasting in the content of the plain text file you attached.
https://mtg.dragonshield.com/decks -> Import -> Paste In List

<img width="769" alt="image" src="https://github.com/Hottemax/MtgCsvHelper/assets/17760200/1f1dfe80-ae46-4cd0-8fec-f9d92e447e71">

In MTGOGoldfish, you can not export collections (but not individual decks) as csv: https://www.mtggoldfish.com/portfolio/export

Let me know if this helps.

**Comment by gabrieldesouza02** [comment]
> Hi, the tool is mainly for converting between the different csv formats, currently not plain text. Also, it seems your list is a deck list, not really a collection.
> 
> In DragonShield, you can import your decklist by pasting in the content of the plain text file you attached. https://mtg.dragonshield.com/decks -> Import -> Paste In List
> <img alt="image" width="769" src="https://user-images.githubusercontent.com/17760200/271029289-1f1dfe80-ae46-4cd0-8fec-f9d92e447e71.png">
> 
> In MTGOGoldfish, you can not export collections (but not individual decks) as csv: https://www.mtggoldfish.com/portfolio/export
> 
> Let me know if this helps.

this does help, thank you! I figured that the plain txt was the issue, I didn't know that a decklist was different from a collection, on mtggoldfish, thanks again!
