### ISSUE TITLE
DragonShield to Moxfield ‘invalid header: CardName’

### ISSUE THREAD

**Issue by osnielvaldivia** [Hottemax/MtgCsvHelper#7]
**Describe the bug**
Importing my all cards collection csv directly exported from iOS MTG Scanner - Dragon Shield app

**To Reproduce**
1. Go to the web app
2. Click on import from 'DragonShield'
3. Click on export to 'Moxfield'
4. Click convert

[All%5FCARDS.csv](https://github.com/Hottemax/MtgCsvHelper/files/14908530/All.5FCARDS.csv)

**Comment by Hottemax** [comment]
@osnielvaldivia Thanks for reporting this issue.

This is related to Dragonshield having two different csv formats:

Web:
mtg.dragonshield.com
Folder Name,Quantity,Trade Quantity,Card Name,Set Code,Set Name,Card Number,Condition,Printing,Language,Price Bought,Date Bought,LOW,MID,MARKET

From the app:
Quantity, Name, CardNumber, Expansion Code, Expansion Name, PurchasePrice, Foil, Condition, Language, PurchaseDate, Single Current Price, Total Current Price

*rolleyes*

I can support both as _DragonShield - App_ and _DragonShield - Web_
I think I can finish this soon, until then it will work when you export your inventory from mtg.dragonshield.com

**Comment by osnielvaldivia** [comment]
If you’d like to copy the double sided card list I ended up hard coding it here https://github.com/osnielvaldivia/dragon-shield-to-moxfield/blob/48d3210dc6873542ec319f0929c31c717ec19687/index.html#L201 


Maybe there is a way to get that list from Scryfalls API. Updating the list every time double sided cards are released is annoying


Thanks for looking into this, I did not know the mobile and desktop differences for export

**Comment by Hottemax** [comment]
> If you’d like to copy the double sided card list I ended up hard coding it here https://github.com/osnielvaldivia/dragon-shield-to-moxfield/blob/48d3210dc6873542ec319f0929c31c717ec19687/index.html#L201
> 
> Maybe there is a way to get that list from Scryfalls API. Updating the list every time double sided cards are released is annoying

Yes, I am already using Scryfall to amend cards that are not in the double-faced format without the use of a static list:
https://github.com/Hottemax/MtgCsvHelper/blob/main/MtgCsvHelper/Converters/CardNameConverter.cs
https://github.com/Hottemax/MtgCsvHelper/blob/9f61ca2e823e18f65c0d50e2651e2e9f64028fc7/MtgCsvHelper/Services/CachedMtgApi.cs#L32

**Comment by Hottemax** [comment]
@osnielvaldivia since I don't know what I can do here if I encounter such faulty input, I would only consider this for development if the input gets fixed by Dragonshield.
